[tool.ruff]
target-version = "py314"
line-length = 88

exclude = [
    ".venv", 
    ".git", 
    "__pycache__", 
    "docs",
    "tests"
]

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "UP",
    "B",
    "N",
    "SIM",
    "TID",
    "ARG",
    "ANN",
    "ERA",
    "RUF",
    "ASYNC",
    "PERF",
    "LOG",
    "C90",
]

ignore = ["E501", "ANN002", "RUF001"]

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = false
suppress-none-returning = false

[tool.ruff.lint.per-file-ignores]
"cog/*" = ["ARG001", "ARG002"]

[tool.ruff.lint.isort]
known-first-party = ["cog", "modules", "Lyxios", "main", "PARAMS"]
combine-as-imports = true
force-sort-within-sections = true

[tool.ruff.format]
line-ending = "lf"
quote-style = "double"
docstring-code-format = true
skip-magic-trailing-comma = false