[tool.ruff]
# Options globales (Linter/Checker)
target-version = "py312"
line-length = 88
# NOTE : "line-ending" a été déplacé dans [tool.ruff.format]

[tool.ruff.lint]
select = [
    "E", "W", "F", "I", "UP",
    "B",
    "N",
    "SIM",
    "TID",
    "ARG",
    "ANN",
    "ERA",
    "RUF",
]

exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "docs",
]

ignore = ["E501", "ANN001", "ANN401", "ARG001", "ARG002", "RUF001"] 

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = true  
suppress-none-returning = false

[tool.ruff.lint.per-file-ignores]

[tool.ruff.lint.isort]
known-first-party = ["cogs", "modules", "Lyxios", "main", "PARAMS"]
combine-as-imports = true
force-sort-within-sections = true

# NOUVELLE SECTION - Ceci est l'endroit correct pour les options de formatage
[tool.ruff.format]
# C'est ici que 'line-ending' doit se trouver.
line-ending = "lf"
quote-style = "double"
docstring-code-format = true
skip-magic-trailing-comma = false